### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by ebattenberg** [ebattenberg/ggmm#14]
This should have py3 compatbility because py2 is really old.

**Comment by Chocobo1** [comment]
Do you want to drop support for py2?
If no, it's possible to use [six](https://github.com/benjaminp/six) as a compatibility layer.

**Comment by ebattenberg** [comment]
I know six, [python-future](http://python-future.org/), and [2 to 3](https://docs.python.org/2/library/2to3.html) pretty well.  I'd prefer to keep compatibility for both py2/3 but py3 should be preferred going forward as numpy is dropping support for py2 soon.  

I currently don't have easy (personal) access to a machine with a CUDA GPU which is why I haven't been contributing myself.

**Comment by Chocobo1** [comment]
>but py3 should be preferred going forward as numpy is dropping support for py2 soon.

I've submitted PR #15.

**Comment by ebattenberg** [comment]
Addressed in #15.
